### ISSUE TITLE
Lab 2 - Regression table

### ISSUE THREAD

**Issue by sjone128** [Watts-College/cpp-525-sum-2022#2]
Hi, 
Quick question. 
Running the linear model for the first regression and the Post coefficient is missing. I'm not sure what I'm missing. 

-thanks!
`
 ```{r}

reg_vand <- lm(Vandalism ~ Months + Group + Post,  data = data)

stargazer(reg_vand, 
          type = "text",
          dep.var.labels = ("Vandalism Calls"),
          column.labels = "",
          covariate.labels = c("Months", "Treatment", "Post Treatment"),
          omit.stat = "all",
          digits = 3)
```
 `

**Comment by Dselby86** [comment]
Don't use the Months variable. Instead use an interaction term between
treatment and post.

that can either look like this:
lm(Vandalism ~ Treatment + Post + Treatment:Post)

or

lm(Vandalism ~ Treatment * Post)

**Comment by sjone128** [comment]
Dr. Selby,

Thanks for your help! 

Sarah
