### ISSUE TITLE
Magnitude of OV and IV

### ISSUE THREAD

**Issue by dholford** [Watts-College/cpp-525-sum-2022#3]
@Dselby86,

How do we account for possible differences in how much of the variance / program impact the OV and IV may explain? The way I understand it, some of the variance / impact on the dependent variable is actually the result of the omitted variable and not the independent variable. So, we choose an instrumental variable to act as a sort of proxy. In doing so, we make sure the independent variable's impact on the dependent variable isn't overestimated. However, how could you ever know if you are picking an instrumental variable that has a similar overlap with the policy variable as the omitted variable? Or is that not actually a concern? Or am I totally missing something?

Thanks,
Dylan

**Comment by Dselby86** [comment]
The question you asked is the pivotal question of Instrumental Variables.
And the answer is you don't know if the variable is correcting for the
bias.  So what you have to do is use theory and logic to justify why the
instrument you chose is a good one.

One thing to correct in your language, you don't use the Instrumental
variable as a proxy for the OV.  Instead, you the instrumental variable to
predict the OV.  A proxy variable is when you have something correlated
with an unobserved variable.  An example of a proxy variable is using
Education as a proxy for cognitive ability or intelligence (obviously that
is a flawed, but proxies always are)

**Comment by dholford** [comment]
Got it. So essentially we are making two assumptions related to the IV / policy variable relationship:

1. That the IV is correlated to the dependent variable only through the policy variable
2. That the IV has a similar overlap with the policy variable as the omitted variable

Thanks!
